### ISSUE TITLE
stress-test.ipynb: wrong max_time calculation: ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by tlvu** [Ouranosinc/PAVICS-e2e-workflow-tests#102]
I have a feeling this `return max(self.times)` should have been something like `return self.max_time` (a constant set in `__init__()`), @ahandan what do you think?
```
12:28:26  Input In [2], in StressTestResult.max_time(self)
12:28:26       95 @property
12:28:26       96 def max_time(self):
12:28:26  ---> 97     return max(self.times)
```

Full Jenkins error:
```
12:28:26  _____________________ notebooks/stress-tests.ipynb::Cell 3 _____________________
12:28:26  Notebook cell execution failed
12:28:26  Cell 3: Cell execution caused an exception
12:28:26  
12:28:26  Input:
12:28:26  # NBVAL_IGNORE_OUTPUT
12:28:26  
12:28:26  # Executing WPS test on multiple threads
12:28:26  wps_urls = [
12:28:26      f"{TWITCHER_URL}/{bird}/wps?service=wps&request=getcapabilities"
12:28:26      for bird in TEST_WPS_BIRDS
12:28:26  ]
12:28:26  
12:28:26  for execution, url in enumerate(wps_urls):
12:28:26      run_threads(target_test = stress_test,
12:28:26                  url = url,
12:28:26                  execution_id = execution,
12:28:26                  n_threads = TEST_N_THREADS_WPS,
12:28:26                  runs_per_threads = TEST_RUNS_WPS)
12:28:26  
12:28:26  Traceback:
12:28:26  
12:28:26  ---------------------------------------------------------------------------
12:28:26  ValueError                                Traceback (most recent call last)
12:28:26  Input In [4], in <module>
12:28:26        4 wps_urls = [
12:28:26        5     f"{TWITCHER_URL}/{bird}/wps?service=wps&request=getcapabilities"
12:28:26        6     for bird in TEST_WPS_BIRDS
12:28:26        7 ]
12:28:26        9 for execution, url in enumerate(wps_urls):
12:28:26  ---> 10     run_threads(target_test = stress_test,
12:28:26       11                 url = url,
12:28:26       12                 execution_id = execution,
12:28:26       13                 n_threads = TEST_N_THREADS_WPS,
12:28:26       14                 runs_per_threads = TEST_RUNS_WPS)
12:28:26  
12:28:26  Input In [3], in run_threads(target_test, url, execution_id, n_threads, runs_per_threads)
12:28:26       34 for thread in threads:
12:28:26       35     thread.join()
12:28:26       37 assert (
12:28:26       38     stress_test_progression.failed_threads_count == 0
12:28:26  ---> 39 ), stress_test_progression.fail_report()
12:28:26       41 print(f"All threads passed {target_test.__name__} function.")
12:28:26  
12:28:26  Input In [2], in StressTestProgression.fail_report(self)
12:28:26       46     i+= 1
12:28:26       48 report_error_message += f"\n\n\n Failed Test"
12:28:26  ---> 49 report_error_message += f"\n {failed_result}"
12:28:26       51 report_error_message += f"\n\n === Exceptions ==="
12:28:26       52 for i, exception in enumerate(failed_result.request_exceptions):
12:28:26  
12:28:26  Input In [2], in StressTestResult.__str__(self)
12:28:26      124     summary = [
12:28:26      125         f"Detected {self.sum_err_code} erroneous HTTP codes not equal to expected {self.code}."
12:28:26      126     ]
12:28:26      127 elif self.status == -2:
12:28:26      128     summary = [
12:28:26      129         f"Detected regression with long request time.",
12:28:26  --> 130         f"Expected max-avg-time: ({self.max_avg_time:.3f}s <= {self.max_time:.3f}s)."
12:28:26      131     ]
12:28:26      132 elif self.status == -3:
12:28:26      133     summary = [
12:28:26      134         f"Maximum number of timeout ({self.timeout_abort}s) requests exceeded ({self.timeout_count}).",
12:28:26      135         "Test was aborted to avoid further delays."
12:28:26      136     ]
12:28:26  
12:28:26  Input In [2], in StressTestResult.max_time(self)
12:28:26       95 @property
12:28:26       96 def max_time(self):
12:28:26  ---> 97     return max(self.times)
12:28:26  
12:28:26  ValueError: max() arg is an empty sequence
```

**Comment by fmigneault** [comment]
Seems outdated. No `max_time` defined in `__init__`.

**Comment by tlvu** [comment]
> Seems outdated. No `max_time` defined in `__init__`.

Maybe it's probably this fact that is the issue?  I still see this intermittently.  Hard to reproduce due to intermittent behavior so hard to test any fixes.

**Comment by fmigneault** [comment]
I do not understand how using a constant would improve? 
That would only set the value each time rather than computing it when calling the property, but the compared value would end up the same.

What the test relies on is that each *avg-time* from test requests is lower than the `max_avg_time` to consider them to be responding sufficiently fast. 

What might be confusing is that, the `max(self.times)` (i.e.: `max_time` property) that is displayed in the error message *is not actually the same* as in the `result.avg_time > max_avg_time` fail check. You could have a longer time than the max for 1 request, but on average, those end up lower than the maximum permitted, because it is only 1 occurrence out of 100. There could be another `max_abs_time` parameter to compare that all times are lower using a failing check `self.max_time > max_abs_time`.

**Comment by tlvu** [comment]
Just to be clear I have not touched this issue because I do not fully understand the logic behind the test and it does not happen very often, probably once every 2 months so very hard to test any fixes.  You might want to ask the original author of this test.  I want to avoid give my opinion when I do not fully understand the problem.

**Comment by fmigneault** [comment]
@ahandan and I are the designers of the test.

If I recall correctly, a `self.max_time > max_abs_time` check was not implemented purposely to avoid failing tests if only 1-2 sporadic responses failed within the max-time, but that overall it always behaves correctly and fast. If something started reacting slowly consistently, it would be reflected on the average, but not for a few instances, which usually do occur sporadically.

What could be done is to add an extra check of top-k max-times, where there must not be more than `max_time_occurances` with a time above `max_abs_time`. So, the test would be validating both on average and per-request with some room for errors. If you want stricter checks, the `max_time_occurances` could be set to zero to allow none.

How does that sound?

**Comment by tlvu** [comment]
Just replying from the stack-trace I see.  Sorry if my guess is wrong because I do not fully understand the algorithm.

So we have a this error `ValueError: max() arg is an empty sequence` at `return max(self.times)` which suggests `self.times` is empty.

So shouldn't the fix is to ensure `self.times` is not empty?

If `self.times` is the collection of the time it takes for each run, does this means no run has occurred?  This is very weird.  Is there a race-condition when updating this variable?

**Comment by fmigneault** [comment]
Yes, we should fix it. 
Looking quickly at the code, it seems the only case `times` attribute would be empty is if every single run returned another response than Timeout or HTTP OK (i.e.: the `except` followed by `else` blocks).
I can open a PR moving the times out of the "if". I'm curious which situation could cause that...


```python
        try:
            resp = requests.request(method, url, timeout=abort_timeout, **req_kwargs)
            resp.raise_for_status()
        except requests.exceptions.RequestException as exe:
            code = 0
            if isinstance(exe, requests.exceptions.Timeout):
                code = 408 # read timeout
                result.times.append(abort_timeout)
                result.timeout_count += 1
            else:
                code = exe.response.status_code
            result.codes.append(code)
            result.request_exceptions.append(exe)
            stress_test_progression.failed_requests_count += 1
        else:
            result.codes.append(resp.status_code)
            result.times.append(time.perf_counter() - start)
            result.timestamps.append(datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
```
