### ISSUE TITLE
Add SAlib to environment

### ISSUE THREAD

**Issue by huard** [Ouranosinc/PAVICS-e2e-workflow-tests#127]
``pip install SALib``

Needed by Richard for sensitivity analyses.

**Comment by tlvu** [comment]
@huard il y a un package Conda https://anaconda.org/conda-forge/salib.  J'imagine que je peux le prendre ou il faut le package Pip?

**Comment by tlvu** [comment]
For new RavenPY nb https://github.com/CSHS-CWRA/RavenPy/pull/320

**Comment by huard** [comment]
Oui, tu peux utiliser le package conda.

**Comment by tlvu** [comment]
Beta Jupyter env has SAlib.
