### ISSUE TITLE
Re-enable the ESGF notebooks for the CWT API 

### ISSUE THREAD

**Issue by huard** [Ouranosinc/PAVICS-e2e-workflow-tests#13]
The AIMS2 server issues should now be fixed.

**Comment by tlvu** [comment]
WIP 
https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/tree/add-esgf-notebooks
http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/add-esgf-notebooks/

**Comment by tlvu** [comment]
Jenkins job to test ESGF notebooks: http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/enable-esgf-notebooks-in-jenkins/

**Comment by tlvu** [comment]
PR to start fixing ESGF notebooks to pass under Jenkins https://github.com/ESGF/esgf-compute-api/pull/64

**Comment by tlvu** [comment]
@huard should we close this issue?  The `vcs` package was removed from our Jupyter env in PR https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/95 so ESGF notebooks won't work anymore.
