### ISSUE TITLE
Not able to pull latest RavenPy 0.6.0 in a full rebuild

### ISSUE THREAD

**Issue by tlvu** [Ouranosinc/PAVICS-e2e-workflow-tests#77]
Triggered a full rebuild on DockerHub today (https://hub.docker.com/repository/registry-1.docker.io/pavics/workflow-tests/builds/b5e792c8-0ad7-481a-a5d4-663494cd7c19) and RavenPy is still at `0.5.2` while the latest one on https://anaconda.org/conda-forge/ravenpy/ is `0.6.0`.

DockerHub build logs: [pavics-workflow-tests-builds-b5e792c8-0ad7-481a-a5d4-663494cd7c19.txt](https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/files/6679192/pavics-workflow-tests-builds-b5e792c8-0ad7-481a-a5d4-663494cd7c19.txt)

It's as if some indirect dependency in the environment.yml file (https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/blob/1ce2e5445600be8808fa9282b95034986ade6aea/docker/environment.yml) pinned RavenPy version.

Tried forcing `ravenpy==0.6.0` and stuck at dependency solving:
```
$ docker run -it --rm --name test-ravenpy-pinning -u 0 --entrypoint bash pavics/workflow-tests:210527.1-update20210618
(base) root@f71b6fb1f025:/# conda activate birdy
(birdy) root@f71b6fb1f025:/# conda install -c conda-forge -c cdat -c bokeh -c plotly -c defaults -n birdy ravenpy==0.6.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /-
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
```

FYI @Zeitsperre

**Comment by tlvu** [comment]
Tried a full rebuild, unpinning `cftime`, still not pulling latest RavenPy, see commit https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/commit/b766d3c49bef91518b7d5e732df85ee3fa978f7f, dockerhub build log https://hub.docker.com/repository/registry-1.docker.io/pavics/workflow-tests/builds/2c5d3b67-e29f-45c9-a110-3861a714f36b

**Comment by Zeitsperre** [comment]
Would pulling that version of RavenPy be an acceptable option? I wonder if conda-forge allows us to park specific version of binaries as only privately-accessible?

**Comment by tlvu** [comment]
> Would pulling that version of RavenPy be an acceptable option? I wonder if conda-forge allows us to park specific version of binaries as only privately-accessible?

Not sure what you mean.

FYI I just triggered a full rebuild on DockerHub again and it still did not pickup the new ravenpy 0.6.0 build1.  The build1 was from this feedstock https://github.com/conda-forge/ravenpy-feedstock/pull/6 ?

**Comment by Zeitsperre** [comment]
Still? Alright. More to look into.

**Comment by Zeitsperre** [comment]
@tlvu Try rebuilding now. I think it should work.

**Comment by tlvu** [comment]
@Zeitsperre https://github.com/conda-forge/ravenpy-feedstock/pull/7 did it.  I was able to pull latest RavenPy in a full Jupyter env build, thanks !
